image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # Redis
  - port: 6379
    onOpen: ignore

vscode:
  extensions:
    - castwide.solargraph
    - rebornix.ruby
    - vortizhe.simple-ruby-erb
    - wingrunr21.vscode-ruby
