image:
  file: .official.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # Redis
  - port: 6379
    onOpen: ignore

tasks:
  - name: Install zsh
    command: ./bin/gitpod/install_zsh

vscode:
  extensions:
    - castwide.solargraph
    - rebornix.ruby
    - vortizhe.simple-ruby-erb
    - wingrunr21.vscode-ruby
